# Generated by Django 6.0.4 on 2026-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_areapermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areapermission',
            name='area',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('products', 'Products'), ('reports', 'Reports'), ('user_management', 'User Management')], max_length=50),
        ),
    ]
