# Generated by Django 6.0.4 on 2026-04-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('own', 'Own Site'), ('ondc', 'ONDC')], max_length=20)),
                ('order_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('fulfilment', models.CharField(choices=[('amazon', 'Amazon'), ('self', 'Self'), ('flipkart', 'Flipkart')], max_length=20)),
                ('is_b2b', models.BooleanField(default=False)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_gate', 'In Gate'), ('dispatched', 'Dispatched')], default='pending', max_length=20)),
                ('state_code', models.CharField(max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
