# Generated by Django 6.0.4 on 2026-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_order_state_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('Return In Transit', 'Return In Transit'), ('Return Arrived', 'Return Arrived')], default='pending', max_length=20),
        ),
    ]
