# Generated by Django 6.0.4 on 2026-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sgst',
            field=models.FloatField(default=0),
        ),
    ]
