# Generated by Django 6.0.4 on 2026-04-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_order_amount_alter_order_cgst_alter_order_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
