# Generated by Django 6.0.4 on 2026-04-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_order_is_stock_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_replacement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='replacement_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return In Transit', 'Return In Transit'), ('Return Arrived', 'Return Arrived')], default='pending', max_length=20),
        ),
    ]
