# Generated by Django 6.0.4 on 2026-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_order_is_replacement_order_replacement_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
    ]
