# Generated by Django 6.0.4 on 2026-04-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_state_alter_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
