# Generated by Django 6.0.4 on 2026-05-01 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_order_state'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='order',
        #     name='state',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.state'),
        # ),
    ]
