# Generated by Django 6.0.4 on 2026-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_order_state'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='State',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #         ('code', models.CharField(max_length=5)),
        #     ],
        # ),
        # migrations.AlterField(
        #     model_name='order',
        #     name='state_code',
        #     field=models.CharField(blank=True, max_length=10, null=True),
        # ),
    ]
