# Generated by Django 6.0.4 on 2026-05-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_state_alter_order_state_code_alter_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Hycom', max_length=200)),
                ('company_subtitle', models.CharField(blank=True, default='Management System', max_length=200)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_phone', models.CharField(blank=True, default='', max_length=50)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_gstin', models.CharField(blank=True, default='', max_length=30)),
                ('footer_note', models.TextField(blank=True, default='This is a system generated invoice.')),
                ('signature_label', models.CharField(default='Authorised Signature', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ORDER_UPDATE', 'Order Update'), ('INVOICE', 'Invoice')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'is_active'], name='master_noti_categor_29c99c_idx')],
                'unique_together': {('category', 'email')},
            },
        ),
    ]
