# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_invoicesetting_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesetting',
            name='company_cin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='company_msme',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='company_pan',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_default_hsn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_delivery_prefix',
            field=models.CharField(blank=True, default='DN', max_length=30),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_doc_prefix',
            field=models.CharField(blank=True, default='DC', max_length=30),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_footer_note',
            field=models.TextField(blank=True, default='1) Please verify quantity and condition of goods upon receipt.\n2) Shortage, damage, or quality issues must be reported within 24 hours of receipt of goods.'),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_insurance_note',
            field=models.TextField(blank=True, default='Materials are covered under the Marine Cargo Annual Turnover Policy.'),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_terms',
            field=models.CharField(blank=True, default='Ex Works', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_transport_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicesetting',
            name='dc_vehicle_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='dc_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
