# Generated by Django 6.0.4 on 2026-04-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_order_is_stock_updated'),
        ('returns', '0001_initial'),
        ('stock', '0005_alter_product_category_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_arrived_date', models.DateField(blank=True, null=True)),
                ('customer_review', models.TextField(blank=True)),
                ('quality_check', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('checked_by', models.CharField(blank=True, max_length=100)),
                ('qc_date', models.DateField(blank=True, null=True)),
                ('qc_review', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], max_length=20)),
                ('is_stock_added', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
