# Generated by Django 6.0.4 on 2026-04-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='return',
            name='product',
        ),
        migrations.RemoveField(
            model_name='return',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='customer_review',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='qc_date',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='qc_review',
        ),
        migrations.AddField(
            model_name='return',
            name='type',
            field=models.CharField(choices=[('return', 'Return'), ('cancel', 'Cancellation')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return'),
            preserve_default=False,
        ),
    ]
