# Generated by Django 6.0.4 on 2026-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_remove_return_condition_remove_return_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='customer_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='qc_checked_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='qc_message',
            field=models.TextField(blank=True),
        ),
    ]
