# Generated by Django 6.0.4 on 2026-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
