# Generated by Django 6.0.4 on 2026-04-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_gender_product_style'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'style', 'gender', 'color', 'size')},
        ),
    ]
