# Generated by Django 6.0.4 on 2026-05-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_product_category_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.CharField(choices=[('Hycom', 'Hycom'), ('Amazon', 'Amazon'), ('Flipkart', 'Flipkart')], default='Hycom', max_length=20),
        ),
    ]
